services:
  db:
    build: .
    volumes:
      - /var/lib/mysql
      - ./:/home/files/
    environment:
      - HOST_HOSTNAME=localhost
      - MYSQL_ROOT_PASSWORD=bd
      - MYSQL_DATABASE=projeto_bd
    networks:
      back-tier:
        ipv4_address: 172.18.0.2

networks:
  back-tier:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
