services:
  db:
    image: "mysql:8"
    volumes:
      - /var/lib/mysql
    environment:
      - HOST_HOSTNAME=localhost
      - MYSQL_ROOT_PASSWORD=bd
      - MYSQL_DATABASE=projeto_bd
  node:
    build: .
    user: node
    environment:
      - NODE_ENV=production
    expose:
      - "3333"
    command: ["node", "dist/index.js"]
    links:
      - db
