services:
  db:
    build: .
    volumes:
      - /var/lib/mysql
      - ./:/var/lib/mysql-files/
    environment:
      - HOST_HOSTNAME=localhost
      - MYSQL_ROOT_PASSWORD=bd
      - MYSQL_DATABASE=projeto_bd
    networks:
      back-tier:
        ipv4_address: 172.20.0.2

networks:
  back-tier:
    ipagm:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
