services:
  node:
    image: "node:8"
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app-bd:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    links:
      - db
  db:
    image: "mysql:8"
    volumes:
      - /var/lib/mysql
    environment:
      - HOST_HOSTNAME=localhost
      - MYSQL_ROOT_PASSWORD=bd
      - MYSQL_DATABASE=projeto_bd
